apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
spec:
  ports:
      -
          port: 8761
          targetPort: 8761
  selector:
    app: gateway
  type: LoadBalancer
