server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: eventos
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: dd
    password: ddd
  jwt:
    config:
      type: signed