server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://35.238.241.13:8761/eureka/
    register-with-eureka: true

spring:
  application:
    name: eventos
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  cache:
    ehcache:
      config: classpath:ehcache.xml
  jmx:
    enabled: false

  datasource:
      url: jdbc:sqlserver://projeto-bora.database.windows.net:1433;database=BoraDB;user=bora-project@projeto-bora;password=Projeto@bor;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      username: bora-project
      password: Projeto@bor
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      platform: mssql

logging:
  level:
    org.hibernate.type: trace
