apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: default
spec:
  ports:
      -
          port: 8081
          targetPort: 8081
  selector:
    app: eureka
  type: LoadBalancer
