INSERT INTO TBD_USUARIO ( APELIDO , NOME, CELULAR , EMAIL ,SENHA ) VALUES ('Bru','Bruno',12345678911,'bruno@email.com','123456');
INSERT INTO TBD_USUARIO ( APELIDO , NOME, CELULAR , EMAIL ,SENHA ) VALUES ('admin','admin',12345678911,'admin@email.com','123456');


INSERT INTO TBD_ENDERECO (BAIRRO, CEP, CIDADE, ESTADO, NUMERO, RUA) VALUES ('Jd. bela vista', '000123','São Paulo', 'SP', '444', 'Av. paulista');
INSERT INTO TBD_CATEGORIA (NOME_CATEGORIA) values ('Esportes');
INSERT INTO TBD_CATEGORIA (NOME_CATEGORIA) values ('Festas');
INSERT INTO TBD_CATEGORIA (NOME_CATEGORIA) values ('Jogos');

INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Futebol',1);
INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Volei',1);
INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Tenis',1);
INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Basquete',1);

INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Bloquinho',2);
INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Festival',2);
INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Balada',2);

INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('RPG',3);
INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Tabuleiro',3);
INSERT INTO TBD_SUB_CATEGORIA ( NOME_SUB_CATEGORIA , CATEGORIA_ID_FK ) values ('Games',3);

INSERT INTO TBD_EVENTO ( DATA_HORA_INICIO , DATA_HORA_FIM , DESCRICAO , ENDERECO_ID_FK , IS_PRIVADO , NOME_EVENTO , SUB_CATEGORIA_ID_FK ) VALUES (15,16,'Fut de sabadao',1,0,'FUTEBAS',1);
INSERT INTO TBD_EVENTO ( DATA_HORA_INICIO , DATA_HORA_FIM , DESCRICAO , ENDERECO_ID_FK , IS_PRIVADO , NOME_EVENTO , SUB_CATEGORIA_ID_FK ) VALUES (15,16,'Pelada do pelé',1,0,'Pelada do pelé',1);
INSERT INTO TBD_EVENTO ( DATA_HORA_INICIO , DATA_HORA_FIM , DESCRICAO , ENDERECO_ID_FK , IS_PRIVADO , NOME_EVENTO , SUB_CATEGORIA_ID_FK ) VALUES (15,16,'volei alopradasso',1,0,'Volei do mal',2);







/*
 select * from tbd_evento e
INNER JOIN tbd_categoria c
on e.categoria_id_fk = c.id_categoria
INNER JOIN tbd_sub_categoria sc
on c.categoria_id_fk = sc.id_sub_categoria 
where nome_sub_categoria = 'Futebol';
 */

