apiVersion: v1
kind: Service
metadata:
  name: eventos-service
  namespace: default
spec:
  ports:
      -
          port: 8087
          targetPort: 8087
  selector:
    app: auth
  type: LoadBalancer
