spring:
    application:
        name: gateway
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
    port: 8080
    servlet:
        context-path: /gateway
eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://35.238.241.13:8761/eureka/
        fetch-registry: true
        register-with-eureka: true

zuul:
    sensitive-headers: Cookie

ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
