server:
    port: 8083

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/
        register-with-eureka: true

spring:
    application:
        name: auth

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create-drop

    jmx:
        enabled: false

    datasource:
        url: jdbc:h2:file:./db/database;AUTO_SERVER=TRUE
        username: sa
        password:
        driver-class-name: org.h2.Driver
        platform: h2

    h2:
        console:
            enabled: true
            path: /console

jwt:
    config:
        type: signed
