server:
    port: 8085

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/
        register-with-eureka: true

spring:
    application:
        name: pesquisa
    data:
        mongodb:
              uri: mongodb+srv://SVN7V:futebol1996santos@jesusdb-csczi.azure.mongodb.net/test?retryWrites=true&w=majority
            # uri: mongodb://127.0.0.1:27017/bora-db

