spring:
  application:
    name: registry

server:
  port: 8081

eureka:
  client:
    registry-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka/
